name: on-push-jobs
on: [push]
jobs:
  build-and-test-slurm-containers:
    strategy:
      matrix:
        slurm-tag: ["slurm-20-02-1-1"]
    runs-on: ubuntu-latest
    env:
      SLURM_TAG: ${{ matrix.slurm-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make build